server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /Users/amrmagdy/git/microservices-spmia/confsvr/src/main/resources/config