eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone : http:localhost:8761/eureka/
 
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/auth/user
    client:
      client-id: first-client
      client-secret: noonewilleverguess           
      

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
          greetings-in:
            destination: greetings
            contentType: application/json
            group: licensingGroup